### ISSUE TITLE
Neural Network Imitator

### ISSUE THREAD

**Issue by Florian-Bolli** [F1Tenth-INI/f1tenth_development_gym#29]
### ToDo:
- [ ] Make NNI planner automatically adjust to required neural network inputs
- [ ] Train with control and state noise on different maps
- [ ] Finetune pretrained (with noise) network with data (without noise) [@nigalsan1]
- [ ] Finetune pretrained (with noise) network with data from physical map (ETF2) [@nigalsan1]
- [ ] Finetune pretrained (with noise) network with pure pursuit [@nigalsan1]
- [ ] Train Neural Network entirely without noise [@Florian-Bolli ]
- [ ] Train NN with pure pursuit for low speed and MPPI for higher speed
- [ ] Analyze data from physical car collected on ETF2

### Longterm:
- [ ] Think of way how to avoid obstacles with non reliable lidar data [@nigalsan1 , @Florian-Bolli]
- [ ] Analyze lidar data from physical car on diferent maps with and without obstacles
- [ ] NNI planner following waypoints generated by MPC

### Other ideas:
- [ ] train with varying friction coefficient to make if tuneable to differen floors

**Comment by nigalsan1** [comment]
I have tried 2 trainings data generation without noise and trained all the models and the had weird behavior in sim
It seemd like they forgot some actions during training and try to overreact in the curves
